apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240612163540.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240612163540.0.0+build.6aff574
  releaseNotes: |
    Release v20240612163540.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-12-06-2024-07-31-24-622863126/where-for-dinner-search-my-apps-bundle@sha256:8243d6c28900a703b462565b9942f80f7729c23da08fa5aac5c32846500125e4
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

